# Generated by Django 4.1.3 on 2023-06-27 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_categoria',
            new_name='product_category',
        ),
    ]
